version: '3.3'

services:
  jenkins:
    image: jenkins/jenkins:${SOFTWARE_VERSION_TAG}
    restart: always
    env_file:
      - .env
    ports:
      - '172.17.0.1:21080:8080'
    volumes:
      - './data:/var/jenkins_home'